export const GLOBAL_CONFIG = {
  PORT: 'PORT',
  MONGO_URI: 'MONGO_URI',
  ALLOWED_ORIGINS: 'ALLOWED_ORIGINS',
  NODE_ENV: 'NODE_ENV',
  JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  JWT_ACCESS_EXPIRATION: 'JWT_ACCESS_EXPIRATION',
  JWT_REFRESH_EXPIRATION: 'JWT_REFRESH_EXPIRATION',
  IS_DEVELOPMENT: 'IS_DEVELOPMENT',
  CLOUDINARY_CLOUD_NAME: 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
  MOCK_USER_ID: 'MOCK_USER_ID',
};

export const AVATAR_IMAGE =
  'https://avatars.githubusercontent.com/u/56169832?v=4';

export const COVER_IMAGE = 'https://picsum.photos/2000/300';
